apiVersion: v1

kind: Service

metadata:
  name: nodeapp-service

spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8090
      targetPort: 5000  
  selector:
    app: nodeapp
