apiVersion: v1
kind: Pod
metadata:
  name: node-app-pod
  labels:
    app: nodeapp
    tier: front-end
spec:
  containers:
    - name: nodeapplatest
      image: harish1206/nodeapp:latest
      ports:
        - containerPort: 5000
